### ISSUE TITLE
make prev/next buttons optional

### ISSUE THREAD

**Issue by fgosfacdjtq** [CSS-Tricks/MovingBoxes#17]
With keyboard nagivation, scroll wheel navigation and mouse-click navigation, the additional buttons should not be mandatory.  It would be nice if the script looked for a div of class mb-left/right and added an anchor to it, instead of forcing it in init().  That would be preferred to adding another config option.

**Comment by Mottie** [comment]
Hiya! Why not just hide the buttons using CSS?

```
.mb-slider .mb-scrollButtons { display: none; }
```

Or, did you want the navigation buttons to be divs instead of anchors? Or are you saying that "buildNav" doesn't really need to be included as an option.

I hadn't thought about adding mousewheel navigation, I'll add some instructions for that using the slider events for others that might be interested when I get more time.

**Comment by fgosfacdjtq** [comment]
I'll use the CSS approach to hiding the buttons, and buildNav should still be an option.

**Comment by fgosfacdjtq** [comment]
Although this works better for me:

```
    .mb-slider .mb-scrollButtons {
        background: 0;
        display: none;
    }
```

The above suggestion still produces 404 errors when loading the arrows image.
