### ISSUE TITLE
Current slide's CSS class doesn't stick -- found a fix

### ISSUE THREAD

**Issue by vossavant** [CSS-Tricks/MovingBoxes#35]
I came across a bug whereby the current slide does not keep the "current" class, and applied a fix to the code.

On line 203 you'll find this:

`var panels = base.$panels.eq(num-1);`

It should be changed to this:

`var panels = base.$panels.eq(num-1).addClass(base.options.currentPanel);`

**Comment by Mottie** [comment]
Hi Vossavant!

Thanks for reporting this. I just updated the plugin to version 2.1.3, but I actually added the code to line 218 (line numbering shifted by one) inside the completed function. I found it was better to update the current class after the animation completed in case there are any css definitions that might conflict with the animation (e.g. width, height or font size settings).

The problem was it was using `$(this)` (no clue why I did that) instead of `base.$panels.eq(num-1)`

Thanks again!
