### ISSUE TITLE
panel height

### ISSUE THREAD

**Issue by aguieb** [CSS-Tricks/MovingBoxes#42]
I am unable to determine how to incurease the panel height. Any idea?

I know we can increase the size of the panel width by updating the panelWidth value in the demo.js file but I don't see the option for the height.

 $('#slider-two').movingBoxes({
      ... 
      panelWidth: .8,     // current panel width adjusted to 70% of overall width
       ...
    });

Please advice...

thanks in advance

**Comment by aguieb** [comment]
FYI... The reason why I need to increase the panel size is because I made the <img> tag in the index.html a background image within the div tag. When I did that the panel size decrease and I am unable to see the whole image.

**Comment by Mottie** [comment]
The height is determined by the panel content. If you look at the [last slide in the first demo](http://chriscoyier.github.com/MovingBoxes/#&slider1=7) you'll see the panel is much taller than the others because of the image size. The second panel is also taller, but because of the text inside the panel. Maybe you just need to set the image dimensions to fix the problem.

**Comment by aguieb** [comment]
never mind...i figured it out.

when using % in CSS it didn't work. I had to use px instead

for example

100% vs 625px

#image3
{
    height:625px;
    background-repeat:no-repeat;
    background-image: url(../demo/c.jpg);
}
