### ISSUE TITLE
Panel Image(Left/Right) disappear when continues sliding is turned on

### ISSUE THREAD

**Issue by aguieb** [CSS-Tricks/MovingBoxes#45]
When wrap is set to true and the focus panel is in the "last" slide and I click forward the left panel image disappears and comes back again.

Same when the "first" panel is set and I click back arrow, the right panel image disappears and comes back again.

BTW.. thanks for fixing issue#44

**Comment by Mottie** [comment]
Yeah, I know that happens. It's because it scrolls to the last cloned panel, then instantly switches to the first. I really didn't want to clone two panels on either end, it just makes things that much more messy. I figured it happened fast enough that it wouldn't be blatantly obvious, if you have the panels sliding much slower, then I'd suggest increasing the `panelWidth` option closer to `1` to fill the whole thing.

I don't want to say I won't ever fix it, but I don't plan on changing it right now.

**Comment by aguieb** [comment]
what i did to make it less noticable is to insert a background image that is non white...

for example

div id="slider-two" style="background-repeat:no-repeat;background-image: url(demo/d.jpg);"
