### ISSUE TITLE
smooth continuous scroll (hover)

### ISSUE THREAD

**Issue by krembo99** [CSS-Tricks/MovingBoxes#73]
Not exactly an issue , more of a request or "how-to" .
Is there a possibility to configure this slider into being a smooth continuous scroll on hover ? something like this for example ? http://www.smoothdivscroll.com/basicDemo.htm

**Comment by Mottie** [comment]
Hmm, it might be possible but it would require some changes to the plugin, I think. The biggest issue I foresee would be to smoothly grow & shrink the panels during the scroll. It may not be an issue for you if the panel size is fixed, but I would still need it to work because that is what this plugin was originally designed to do.

Let me think about it a bit more before I say, "sure why not" or "#$&*%^ this!"

**Comment by krembo99** [comment]
Ok, thanks . I actually almost achieved it by changing the mouse click actions to hover. the only problem is that the animation is going in "steps" because (as I understood from the comments) an event can not really be triggered before another one is ended .

**Comment by Mottie** [comment]
Alright, I've updated the plugin to v2.2.14 and I changed the animation stops to now complete the animation instead of jumping to the end of the animation, so it should be smoother. Check it out in this [mousewheel demo](http://jsfiddle.net/Mottie/jMXx3/751/) and see if that works for you :)

**Comment by krembo99** [comment]
Thanks, that is very cool . as soon as I have time I would like to integrate it in one of my projects . Good job ! thanks again ...
