### ISSUE TITLE
sliding glitch

### ISSUE THREAD

**Issue by ofwalking** [CSS-Tricks/MovingBoxes#8]
Tested it out and noticed there is a sliding glitch when more than 11 panels are used with the following settings... width to 960, panelWidth to 1, reducedSize to 1, and imageRatio to 1.

The glitch is that instead of sliding to the next slide, it will loop through all the panels first before going to the next slide. The same is true for previous slides. Also, when the current state is the last slide and using the navigation to click on the first slide link... it will just pop to the first slide instantly, instead of sliding backwards.

**Comment by Mottie** [comment]
Thanks for the bug report... it's not something obvious, so give me some time to figure out the problem.

**Comment by damonbauer** [comment]
Just adding a comment here:

I've got 30 boxes in the slider, and I've got a problem on panels #25-30.

**Comment by Mottie** [comment]
Ok, I finally found this problem... it turned out to be a jQuery bug (http://bugs.jquery.com/ticket/7193) introduced in version 1.4 and will be fixed in v1.5. But you won't have to wait for jQuery 1.5 because in the latest version (v1.7), I switched the panel positioning from using "left" to "scrollLeft". Please tell me if this fixes your problems as I haven't had a chance to thoroughly test it.

**Comment by damonbauer** [comment]
Mottie -

Looks to be working as expected now. Much thanks for your contributions to this fix.

**Comment by Mottie** [comment]
Great! I'm closing this issue then :)
