### ISSUE TITLE
Initialization and loop problem.

### ISSUE THREAD

**Issue by jackobr** [CSS-Tricks/MovingBoxes#89]
hi, please help me with my demo:

http://digitto.co/slider/

have 3 problems :
- initialization , first screen look strange and i don't know how to correctly initialize it, then after 1 pic moved ,is ok 
- how to do full loop, on the end have 4 empty spaces and then script start not from left end but start on the middle 
- how to re-size , if customer will use lest like 1200 pix on LCD....

Any suggestions, Tnx

**Comment by jackobr** [comment]
new link to demo:

http://prostozusa.info/slider/

TNX

**Comment by Mottie** [comment]
Hi jackobr!

Hmm, yeah I see the problems... maybe this plugin, as it is now, isn't the best choice for you: 
1. It's doesn't really loop like you think it does. It makes a copy of the first slide and sticks it on the end, then makes a copy of the last slide and sticks it on the front; then when the last slide is next to the middle, it switches positioning of the whole group, that's why you see it jump. Some day when I have time, I'll modify this behavior to move each slide independly from the beginning to the end, or vice-versa.
2. MovingBoxes isn't dynamic, it works with a fixed width and not a percentage width. Granted with some creative css media queries you could resize and update MovingBoxes; but again, my time is very limited at the moment, so I don't have time to work  make this kind of modification.

**Comment by jackobr** [comment]
Hi, Mottie, thank you for help and explanation, now understand a little more... best . Jacek
